### ISSUE TITLE
Not working with blender 2.9

### ISSUE THREAD

**Issue by fvmoperator** [dtzxporter/io_model_semodel#10]

**Comment by fvmoperator** [comment]
Not working with 2.9 blender

**Comment by Dhrukiashmi** [comment]
Try to Download from the "**blender-28**" branch instead of the "**master**" branch.

In case if you don't know how to change the branch here below I attach the link for that Branch from there Clone it or Download it and follow the same steps & should work.

[https://github.com/dtzxporter/io_model_semodel/tree/blender-28](url)

I have tested this with the latest version of Blender and it works for me.

**Comment by OkazakiNaoki** [comment]
> Try to Download from the "**blender-28**" branch instead of the "**master**" branch.
> 
> In case if you don't know how to change the branch here below I attach the link for that Branch from there Clone it or Download it and follow the same steps & should work.
> 
> [https://github.com/dtzxporter/io_model_semodel/tree/blender-28](url)
> 
> I have tested this with the latest version of Blender and it works for me.

bro, your link is incorrect. Let me fix it for you.
[Blender 2.8 version branch](https://github.com/dtzxporter/io_model_semodel/tree/blender-28)

**Comment by Dhrukiashmi** [comment]
Thank you for Fixing the link and Sorry for the non-working link.
